### ISSUE TITLE
Issues with encrypted password (v11.0.0)

### ISSUE THREAD

**Issue by exiom-xyz** [thematrixdev/home-assistant-clp#12]
I updated this morning and got my encrypted password via the dev tools, however now I am getting the following errors in my notifications.

>400, message='Bad Request', url='https://clpapigee.eipprod.clp.com.hk/ts1/ms/consumption/history'
500, message='Internal Server Error', url='https://clpapigee.eipprod.clp.com.hk/ts1/ms/renew/fit/dashboard'

>{
  "code": 100001,
  "message": "LR access_token error"
}

**Comment by thematrixdev** [comment]
There is going to be a new release without requiring the use of encrypted password.

**Comment by thematrixdev** [comment]
Try if `v11.1.0` works for you

**Comment by exiom-xyz** [comment]
with `v11.5.0` I am getting the following errors

>2024-10-14 10:36:30.751 ERROR (MainThread) [custom_components.clp.sensor] Daily Generation ERROR: Connection closed
Traceback (most recent call last):
File "/config/custom_components/clp/sensor.py", line 311, in api_request
response.raise_for_status()
File "/usr/local/lib/python3.12/site-packages/aiohttp/client_reqrep.py", line 1121, in raise_for_status
raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 400, message='Bad Request', url='https://clpapigee.eipprod.clp.com.hk/ts1/ms/renew/fit/dashboard'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/config/custom_components/clp/sensor.py", line 178, in wrapper
return await func(self, *args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/clp/sensor.py", line 611, in renewable_get_daily
response = await self.api_request(
^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/clp/sensor.py", line 317, in api_request
response_text = await response.text()
^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/aiohttp/client_reqrep.py", line 1220, in text
await self.read()
File "/usr/local/lib/python3.12/site-packages/aiohttp/client_reqrep.py", line 1178, in read
self._body = await self.content.read()
^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/aiohttp/streams.py", line 360, in read
raise self._exception
File "/config/custom_components/clp/sensor.py", line 314, in api_request
response_data = await response.json()
^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/helpers/aiohttp_client.py", line 80, in json
return await super().json(*args, loads=loads, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/aiohttp/client_reqrep.py", line 1238, in json
await self.read()
File "/usr/local/lib/python3.12/site-packages/aiohttp/client_reqrep.py", line 1178, in read
self._body = await self.content.read()
^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/aiohttp/streams.py", line 360, in read
raise self._exception
aiohttp.client_exceptions.ClientConnectionError: Connection closed
2024-10-14 10:36:30.891 ERROR (MainThread) [custom_components.clp.sensor] Daily Usage ERROR: Connection closed
Traceback (most recent call last):
File "/config/custom_components/clp/sensor.py", line 311, in api_request
response.raise_for_status()
File "/usr/local/lib/python3.12/site-packages/aiohttp/client_reqrep.py", line 1121, in raise_for_status
raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 400, message='Bad Request', url='https://clpapigee.eipprod.clp.com.hk/ts1/ms/consumption/history'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/config/custom_components/clp/sensor.py", line 178, in wrapper
return await func(self, *args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/clp/sensor.py", line 486, in main_get_daily
response = await self.api_request(
^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/clp/sensor.py", line 317, in api_request
response_text = await response.text()
^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/aiohttp/client_reqrep.py", line 1220, in text
await self.read()
File "/usr/local/lib/python3.12/site-packages/aiohttp/client_reqrep.py", line 1178, in read
self._body = await self.content.read()
^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/aiohttp/streams.py", line 360, in read
raise self._exception
File "/config/custom_components/clp/sensor.py", line 314, in api_request
response_data = await response.json()
^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/helpers/aiohttp_client.py", line 80, in json
return await super().json(*args, loads=loads, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/aiohttp/client_reqrep.py", line 1238, in json
await self.read()
File "/usr/local/lib/python3.12/site-packages/aiohttp/client_reqrep.py", line 1178, in read
self._body = await self.content.read()
^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/aiohttp/streams.py", line 360, in read
raise self._exception
aiohttp.client_exceptions.ClientConnectionError: Connection closed

**Comment by thematrixdev** [comment]
Did you use `username` or `account number` to login (at the time when there was no error) ?
Do you have more than one `account number` in your account?

**Comment by thematrixdev** [comment]
Try 11.6.1 please

**Comment by exiom-xyz** [comment]
> Did you use `username` or `account number` to login (at the time when there was no error) ? Do you have more than one `account number` in your account?

Hi, sorry for the late response, I used `username` and it had worked previously and I only have the 1 residential account 

However, having installed `11.7.0` FIT data returns with the following error
>Traceback (most recent call last):
  File "/config/custom_components/clp/sensor.py", line 330, in api_request
    response.raise_for_status()
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client_reqrep.py", line 1121, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 400, message='Bad Request', url='https://clpapigee.eipprod.clp.com.hk/ts1/ms/renew/fit/dashboard'
>
>During handling of the above exception, another exception occurred:
>
>Traceback (most recent call last):
  File "/config/custom_components/clp/sensor.py", line 187, in wrapper
    return await func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/clp/sensor.py", line 667, in renewable_get_daily
    response = await self.api_request(
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/clp/sensor.py", line 345, in api_request
    response_text = await response.text()
                    ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client_reqrep.py", line 1220, in text
    await self.read()
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client_reqrep.py", line 1178, in read
    self._body = await self.content.read()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/streams.py", line 360, in read
    raise self._exception
  File "/config/custom_components/clp/sensor.py", line 342, in api_request
    response_data = await response.json()
                    ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/aiohttp_client.py", line 80, in json
    return await super().json(*args, loads=loads, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client_reqrep.py", line 1238, in json
    await self.read()
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client_reqrep.py", line 1178, in read
    self._body = await self.content.read()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/streams.py", line 360, in read
    raise self._exception
aiohttp.client_exceptions.ClientConnectionError: Connection closed

**Comment by thematrixdev** [comment]
May you try 11.7.1 please?

**Comment by exiom-xyz** [comment]
This version has resolved the issue thanks you!

> May you try 11.7.1 please?
