### ISSUE TITLE
no estimation for smart meter

### ISSUE THREAD

**Issue by kei81131** [thematrixdev/home-assistant-clp#13]
Version: v11.3.2

Config:
```
- platform: clp
  name: CLP-CK # whatever name you like
  username: "1111" # CLP web site username
  password: "2222" # CLP web site password
  timeout: 30
  type: "" # type of data to be shown in state
  get_account: true
  get_bill: true
  get_estimation: true
  get_bimonthly: true
  get_daily: true
  get_hourly: true
```
Sensor-state:

```
state_class: total
last_reset: "2024-10-13T15:00:00"
state_data_type: HOURLY
error: null
account:
  number: "333"
  outstanding: 0
bills:
  bill:
    - total: 694
      transaction_date: "2024-09-17T08:00:00"
      from_date: "2024-08-17T08:00:00"
      to_date: "2024-09-17T08:00:00"
    - total: 724
      transaction_date: "2024-08-16T08:00:00"
      from_date: "2024-07-18T08:00:00"
      to_date: "2024-08-16T08:00:00"
    - total: 738
      transaction_date: "2024-07-17T08:00:00"
      from_date: "2024-06-18T08:00:00"
      to_date: "2024-07-17T08:00:00"
    - total: 519
      transaction_date: "2024-06-17T08:00:00"
      from_date: "2024-05-18T08:00:00"
      to_date: "2024-06-17T08:00:00"
    - total: 484
      transaction_date: "2024-05-17T08:00:00"
      from_date: "2024-04-18T08:00:00"
      to_date: "2024-05-17T08:00:00"
  payment:
    - total: 694
      transaction_date: "2024-10-03T08:00:00"
    - total: 724
      transaction_date: "2024-08-30T08:00:00"
    - total: 738
      transaction_date: "2024-07-29T08:00:00"
    - total: 519
      transaction_date: "2024-07-16T08:00:00"
    - total: 484
      transaction_date: "2024-06-03T08:00:00"
estimation: null
bimonthly:
  - end: "2024-09-17T00:00:00"
    kwh: 464
  - end: "2024-08-16T00:00:00"
    kwh: 484
  - end: "2024-07-17T00:00:00"
    kwh: 496
  - end: "2024-06-17T00:00:00"
    kwh: 385
  - end: "2024-05-17T00:00:00"
    kwh: 359
  - end: "2024-04-17T00:00:00"
    kwh: 349
  - end: "2024-03-15T00:00:00"
    kwh: 218
  - end: "2024-02-16T00:00:00"
    kwh: 198
  - end: "2024-01-17T00:00:00"
    kwh: 252
  - end: "2023-12-15T00:00:00"
    kwh: 279
  - end: "2023-11-17T00:00:00"
    kwh: 375
  - end: "2023-10-17T00:00:00"
    kwh: 443
  - end: "2023-09-15T00:00:00"
    kwh: 452
  - end: "2023-08-17T00:00:00"
    kwh: 537
daily:
  - start: "2024-10-13T00:00:00"
    end: "2024-10-13T15:00:00"
    kwh: 4.5
  - start: "2024-10-12T00:00:00"
    end: "2024-10-12T23:59:59"
    kwh: 9
  - start: "2024-10-11T00:00:00"
    end: "2024-10-11T23:59:59"
    kwh: 4.6
  - start: "2024-10-10T00:00:00"
    end: "2024-10-10T23:59:59"
    kwh: 17.1
  - start: "2024-10-09T00:00:00"
    end: "2024-10-09T23:59:59"
    kwh: 16.2
  - start: "2024-10-08T00:00:00"
    end: "2024-10-08T23:59:59"
    kwh: 16.7
  - start: "2024-10-07T00:00:00"
    end: "2024-10-07T23:59:59"
    kwh: 18.4
  - start: "2024-10-06T00:00:00"
    end: "2024-10-06T23:59:59"
    kwh: 4.6
  - start: "2024-10-05T00:00:00"
    end: "2024-10-05T23:59:59"
    kwh: 6.3
  - start: "2024-10-04T00:00:00"
    end: "2024-10-04T23:59:59"
    kwh: 14.7
  - start: "2024-10-03T00:00:00"
    end: "2024-10-03T23:59:59"
    kwh: 19.3
  - start: "2024-10-02T00:00:00"
    end: "2024-10-02T23:59:59"
    kwh: 18.8
  - start: "2024-10-01T00:00:00"
    end: "2024-10-01T23:59:59"
    kwh: 5.6
hourly:
  - start: "2024-10-13T15:00:00"
    kwh: 0.2
  - start: "2024-10-13T14:00:00"
    kwh: 0.2
  - start: "2024-10-13T13:00:00"
    kwh: 0.2
  - start: "2024-10-13T12:00:00"
    kwh: 0.2
  - start: "2024-10-13T11:00:00"
    kwh: 1
  - start: "2024-10-13T10:00:00"
    kwh: 0.8
  - start: "2024-10-13T09:00:00"
    kwh: 0.2
  - start: "2024-10-13T08:00:00"
    kwh: 0.2
  - start: "2024-10-13T07:00:00"
    kwh: 0.2
  - start: "2024-10-13T06:00:00"
    kwh: 0.2
  - start: "2024-10-13T05:00:00"
    kwh: 0.2
  - start: "2024-10-13T04:00:00"
    kwh: 0.2
  - start: "2024-10-13T03:00:00"
    kwh: 0.2
  - start: "2024-10-13T02:00:00"
    kwh: 0.2
  - start: "2024-10-13T01:00:00"
    kwh: 0.2
  - start: "2024-10-13T00:00:00"
    kwh: 0.2
  - start: "2024-10-12T23:00:00"
    kwh: 0.2
  - start: "2024-10-12T22:00:00"
    kwh: 0.2
  - start: "2024-10-12T21:00:00"
    kwh: 0.2
  - start: "2024-10-12T20:00:00"
    kwh: 0.3
  - start: "2024-10-12T19:00:00"
    kwh: 0.3
  - start: "2024-10-12T18:00:00"
    kwh: 0.4
  - start: "2024-10-12T17:00:00"
    kwh: 0.3
  - start: "2024-10-12T16:00:00"
    kwh: 0.2
  - start: "2024-10-12T15:00:00"
    kwh: 1.2
  - start: "2024-10-12T14:00:00"
    kwh: 1.5
  - start: "2024-10-12T13:00:00"
    kwh: 1.5
  - start: "2024-10-12T12:00:00"
    kwh: 0.3
  - start: "2024-10-12T11:00:00"
    kwh: 0.3
  - start: "2024-10-12T10:00:00"
    kwh: 0.2
  - start: "2024-10-12T09:00:00"
    kwh: 0.2
  - start: "2024-10-12T08:00:00"
    kwh: 0.2
  - start: "2024-10-12T07:00:00"
    kwh: 0.2
  - start: "2024-10-12T06:00:00"
    kwh: 0.2
  - start: "2024-10-12T05:00:00"
    kwh: 0.2
  - start: "2024-10-12T04:00:00"
    kwh: 0.2
  - start: "2024-10-12T03:00:00"
    kwh: 0.2
  - start: "2024-10-12T02:00:00"
    kwh: 0.2
  - start: "2024-10-12T01:00:00"
    kwh: 0.2
unit_of_measurement: kWh
device_class: energy
friendly_name: CLP-CK

```

**Comment by kei81131** [comment]
Error log:
```
This error originated from a custom integration.

Logger: custom_components.clp.sensor
Source: custom_components/clp/sensor.py:177
integration: CLP (documentation, issues)
First occurred: 6:19:17 PM (3 occurrences)
Last logged: 6:39:25 PM

CLP-CK ERROR: time data '' does not match format '%Y%m%d%H%M%S'
Traceback (most recent call last):
  File "/config/custom_components/clp/sensor.py", line 177, in wrapper
    return await func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/clp/sensor.py", line 418, in main_get_estimation
    "estimation_end_date": datetime.datetime.strptime(data['data']['projectedEndDate'], '%Y%m%d%H%M%S'),
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/_strptime.py", line 554, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/_strptime.py", line 333, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data '' does not match format '%Y%m%d%H%M%S'
```

**Comment by thematrixdev** [comment]
https://github.com/thematrixdev/home-assistant-clp/releases/tag/v11.3.3
