### ISSUE TITLE
Connection Closed

### ISSUE THREAD

**Issue by exiom-xyz** [thematrixdev/home-assistant-clp#14]
```This error originated from a custom integration.

Logger: custom_components.clp.sensor
Source: custom_components/clp/sensor.py:187
integration: CLP (documentation, issues)
First occurred: 4:57:03 PM (8 occurrences)
Last logged: 5:12:03 PM

Daily Generation ERROR: Connection closed
Daily Usage ERROR: Connection closed
Traceback (most recent call last):
  File "/config/custom_components/clp/sensor.py", line 330, in api_request
    response.raise_for_status()
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/site-packages/aiohttp/client_reqrep.py", line 1157, in raise_for_status
    raise ClientResponseError(
    ...<5 lines>...
    )
aiohttp.client_exceptions.ClientResponseError: 403, message='Forbidden', url='https://clpapigee.eipprod.clp.com.hk/ts1/ms/profile/accountManagement/loginByPassword'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/clp/sensor.py", line 187, in wrapper
    return await func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/clp/sensor.py", line 379, in auth
    response = await self.api_request(
               ^^^^^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
    )
    ^
  File "/config/custom_components/clp/sensor.py", line 345, in api_request
    response_text = await response.text()
                    ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/aiohttp/client_reqrep.py", line 1256, in text
    await self.read()
  File "/usr/local/lib/python3.13/site-packages/aiohttp/client_reqrep.py", line 1214, in read
    self._body = await self.content.read()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/aiohttp/streams.py", line 389, in read
    raise self._exception
  File "/config/custom_components/clp/sensor.py", line 342, in api_request
    response_data = await response.json()
                    ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/aiohttp_client.py", line 82, in json
    return await super().json(*args, loads=loads, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/aiohttp/client_reqrep.py", line 1272, in json
    await self.read()
  File "/usr/local/lib/python3.13/site-packages/aiohttp/client_reqrep.py", line 1214, in read
    self._body = await self.content.read()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/aiohttp/streams.py", line 389, in read
    raise self._exception
aiohttp.client_exceptions.ClientConnectionError: Connection closed
```

**Comment by kelvinng1** [comment]
I got a similar issue "Connection Closed". 
I have checked and confirmed that my username and password are both correct. (I can login my CLP web account with these credentials)
Also, I have increased my timeout from 30 sec to 90 sec, but the result is the same :-(

My configuration:
HA 
- Core 2024.12.5
- Supervisor 2024.12.0
- Operating System 14.1

home-assistant-clp v11.7.11

Here is my log captured:
```
This error originated from a custom integration.

Logger: custom_components.clp.sensor
Source: custom_components/clp/sensor.py:187
integration: CLP (documentation, issues)
First occurred: 4:37:40 PM (1 occurrences)
Last logged: 4:37:40 PM

CLP ERROR: Connection closed
Traceback (most recent call last):
  File "/config/custom_components/clp/sensor.py", line 330, in api_request
    response.raise_for_status()
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/site-packages/aiohttp/client_reqrep.py", line 1161, in raise_for_status
    raise ClientResponseError(
    ...<5 lines>...
    )
aiohttp.client_exceptions.ClientResponseError: 403, message='Forbidden', url='https://clpapigee.eipprod.clp.com.hk/ts1/ms/profile/accountManagement/loginByPassword'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/clp/sensor.py", line 187, in wrapper
    return await func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/clp/sensor.py", line 379, in auth
    response = await self.api_request(
               ^^^^^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
    )
    ^
  File "/config/custom_components/clp/sensor.py", line 345, in api_request
    response_text = await response.text()
                    ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/aiohttp/client_reqrep.py", line 1260, in text
    await self.read()
  File "/usr/local/lib/python3.13/site-packages/aiohttp/client_reqrep.py", line 1218, in read
    self._body = await self.content.read()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/aiohttp/streams.py", line 392, in read
    raise self._exception
  File "/config/custom_components/clp/sensor.py", line 342, in api_request
    response_data = await response.json()
                    ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/aiohttp_client.py", line 82, in json
    return await super().json(*args, loads=loads, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/aiohttp/client_reqrep.py", line 1276, in json
    await self.read()
  File "/usr/local/lib/python3.13/site-packages/aiohttp/client_reqrep.py", line 1218, in read
    self._body = await self.content.read()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/aiohttp/streams.py", line 392, in read
    raise self._exception
aiohttp.client_exceptions.ClientConnectionError: Connection closed
```

**Comment by FrogBoss74** [comment]
I have the same issue after upgrading to latest homeassitant version. I am using docker version on pi5.
It worked fine before.
